"""rename event response to event answer

Revision ID: 88b5332b9e9b
Revises: 958f61af479d
Create Date: 2026-04-10 19:04:00.897052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88b5332b9e9b'
down_revision: Union[str, Sequence[str], None] = '958f61af479d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('UTC', now())"), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_answers_event_id'), 'event_answers', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_answers_user_id'), 'event_answers', ['user_id'], unique=False)
    op.drop_index(op.f('ix_event_responses_event_id'), table_name='event_responses')
    op.drop_index(op.f('ix_event_responses_user_id'), table_name='event_responses')
    op.drop_table('event_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_to', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_responses_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('event_responses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('event_responses_pkey'))
    )
    op.create_index(op.f('ix_event_responses_user_id'), 'event_responses', ['user_id'], unique=False)
    op.create_index(op.f('ix_event_responses_event_id'), 'event_responses', ['event_id'], unique=False)
    op.drop_index(op.f('ix_event_answers_user_id'), table_name='event_answers')
    op.drop_index(op.f('ix_event_answers_event_id'), table_name='event_answers')
    op.drop_table('event_answers')
    # ### end Alembic commands ###
